config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.index, name='index'),
]

pybo/models.py
from django.db import models


# Create your models here.
class Question(models.Model):
    age = models.TextField()
    gender = models.TextField()
    goal = models.TextField()
    category = models.TextField()
    type = models.TextField()
    grade = models.TextField()
    
class Answer(models.Model):
    obj_finan = models.TextField()
    type_finan = models.TextField()
    obj_insur = models.TextField()
    goal_insur = models.TextField()
    obj_card = models.TextField()

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
import json
from collections import OrderedDict
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from . import recommend,reco,scoring,savings,loan


def home(request):
    return render(request, 'home.html')


@csrf_exempt
def index(request):
    """
    return response
    """
    def get_data(age, gender, goal, category, type,grade):
        d1,d2,d3,d4 = recommend.final_get(age,gender,goal,category,type)
        d5 = reco.general_reco(gender,age)
        d6 = scoring.recommend_product(age, gender)
        d7 = savings.savings(age,gender)
        d8,d9,d10,d11 = loan.main_data(gender,age,grade,goal)
        return d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11
    age = request.POST['age']
    gender = request.POST['gender']
    goal = request.POST['goal']
    category = request.POST['category']
    grade = request.POST['grade']
    type = request.POST['type']
    d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11 = get_data(age,gender,goal,category,type,grade)
    new5 = d5[0][0]['GeumYungHoesa'] + ' No.'+str(d5[0][0]['cardNo'])
    new7 = d7[0][0]['KorCoNm'] +' '+ d7[0][0]['FinPrdtNm']
    new8 = d8[0][0]['KorCoNm'] +' '+ d8[0][0]['FinPrdtNm']
    new9 = d9[0][0]['KorCoNm'] +' '+ d9[0][0]['FinPrdtNm']
    new10 = d10[0][0]['KorCoNm'] +' '+ d10[0][0]['FinPrdtNm']
    new = {'obj_finan' : d1,
           'type_finan' : d2[2][0]['펀드명'],
           'obj_insur' : d3,
           'goal_insur' : d4[0][1]['상품명'],
           'obj_card' : new5,
           'obj_deposit' : d6[0][0]['상품명'],
           'obj_savings' : new7,
           'obj_loan' : new8,
           'obj_mortage' : new9,
           'obj_private_loan' : new10
           }
    

    return render(request, 'index.html', new)

pybo/templates/home.html
<h1>input 입력</h1>
<form action="{% url 'pybo:index'%}" method="POST">
    
    {% csrf_token %}
    <input name="age" placeholder="age"/>
    <input name="gender" placeholder="gender"/>
    <input name="goal" placeholder="goal"/>
    <input name="category" placeholder="category"/>
    <input name="grade" placeholder="grade"/>
    <input name="type" placeholder="type"/>
    <br/>
    <br/>
    age : 나이 <br>
    gender : 남자1, 여자2 <br>
    goal : 설정목표, str <br>
    category : 8대영역 중 1개 <br>
    grade(kcb 연소득 데이터) : 1~7 <br>
    ("2,000만원미만: 1 , 
    2,000만원이상~3,000만원미만: 2, 
    3,000만원이상~4,000만원미만: 3 , 
    4천만원이상~5,000만원미만: 4, 
    5,000만원이상~6,000만원미만: 5, 
    6,000만원이상~7,000만원미만: 6, 
    7,000만원이상: 7) <br>
    type: 적극투자=0, 균형투자=1, 안전투자=2, 보수투자=3 <br>
    <br/>
    <button type="submit">result</button>
</form>

pybo/templates/index.html
<body>
    <h1>result</h1>
    금융상품 : {{type_finan}}<br>

    보험 : {{goal_insur}}<br>

    카드 : {{obj_card}}<br>

    적금 : {{obj_savings}}<br>

    수시입출금통장 : {{obj_deposit}}<br>

    대출 <br>
    전세자금대출 : {{obj_loan}}<br>
    주택자금대출 : {{obj_mortage}}<br>
    개인신용대출 : {{obj_private_loan}}<br>

</body>